# Active visual: DAE (_w). Visual STL (_s.stl) kept on disk; path commented below.
# Spare: visual_parameters_dae.yaml / visual_parameters_stl.yaml
mesh_files:
  link0:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_0_w.dae
        #path: meshes/symphony5/visual/symphony5_0_b.dae
        #path: meshes/symphony5/visual/symphony5_0_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_0_s.stl
  link1:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_1_w.dae
        #path: meshes/symphony5/visual/symphony5_1_b.dae
        #path: meshes/symphony5/visual/symphony5_1_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_1_s.stl
  link2:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_2_w.dae
        #path: meshes/symphony5/visual/symphony5_2_b.dae
        #path: meshes/symphony5/visual/symphony5_2_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_2_s.stl
  link3:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_3_w.dae
        #path: meshes/symphony5/visual/symphony5_3_b.dae
        #path: meshes/symphony5/visual/symphony5_3_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_3_s.stl
  link4:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_4_w.dae
        #path: meshes/symphony5/visual/symphony5_4_b.dae
        #path: meshes/symphony5/visual/symphony5_4_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_4_s.stl
  link5:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_5_w.dae
        #path: meshes/symphony5/visual/symphony5_5_b.dae
        #path: meshes/symphony5/visual/symphony5_5_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_5_s.stl
  link6:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony5/visual/symphony5_6_w.dae
        #path: meshes/symphony5/visual/symphony5_6_b.dae
        #path: meshes/symphony5/visual/symphony5_6_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony5/collision/symphony5_6_s.stl
