mesh_files:
  link0:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_0_w.dae
        #path: meshes/symphony15/visual/symphony15_0_b.dae
        #path: meshes/symphony15/visual/symphony15_0_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_0_s.stl
  link1:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_1_w.dae
        #path: meshes/symphony15/visual/symphony15_1_b.dae
        #path: meshes/symphony15/visual/symphony15_1_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_1_s.stl
  link2:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_2_w.dae
        #path: meshes/symphony15/visual/symphony15_2_b.dae
        #path: meshes/symphony15/visual/symphony15_2_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_2_s.stl
  link3:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_3_w.dae
        #path: meshes/symphony15/visual/symphony15_3_b.dae
        #path: meshes/symphony15/visual/symphony15_3_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_3_s.stl
  link4:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_4_w.dae
        #path: meshes/symphony15/visual/symphony15_4_b.dae
        #path: meshes/symphony15/visual/symphony15_4_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_4_s.stl
  link5:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_5_w.dae
        #path: meshes/symphony15/visual/symphony15_5_b.dae
        #path: meshes/symphony15/visual/symphony15_5_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_5_s.stl
  link6:
    visual:
      mesh:
        package: symphony_description
        path: meshes/symphony15/visual/symphony15_6_w.dae
        #path: meshes/symphony15/visual/symphony15_6_b.dae
        #path: meshes/symphony15/visual/symphony15_6_s.stl
      material: ""
    collision:
      mesh:
        package: symphony_description
        path: meshes/symphony15/collision/symphony15_6_s.stl
