<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>symphony_controllers</name>
  <version>1.0.0</version>
  <description>Symphony ros2 controllers</description>
  <maintainer email="seonmin3425@puloon.co.kr">Puloon</maintainer>
<license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>controller_interface</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>symphony_msgs</depend>
  <depend>control_msgs</depend>
  <depend>rclcpp_action</depend>
  <depend>trajectory_msgs</depend>
  <depend>geometry_msgs</depend>

  <!-- Runtime spawn deps for standard controllers live in symphony_driver (bringup). -->

  <export>
    <build_type>ament_cmake</build_type>
    <controller_interface plugin="${prefix}/symphony_controller_plugins.xml"/>
  </export>
</package>
