# How links connect together
kinematics:
  joint0:
    x: 0.0
    y: 0.0
    z: 0.2021
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint1:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: -1.570796327
    pitch: -1.570796327
    yaw: 0.0
  joint2:
    x: 0.8706
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  joint3:
    x: 0.7635
    y: 0.0
    z: 0.1618
    roll: 0.0
    pitch: 0.0
    yaw: -1.570796327
  joint4:
    x: 0.0
    y: 0.1159
    z: 0.0
    roll: -1.570796327
    pitch: 0.0
    yaw: 0.0
  joint5:
    x: 0.0
    y: -0.1319
    z: 0.0
    roll: 1.570796327
    pitch: 0.0
    yaw: 0.0

